CREATE TABLE IF NOT EXISTS `omr_question_master` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `grade` varchar(50) NOT NULL COLLATE 'utf8mb4_unicode_ci',
  `subject` varchar(100) NOT NULL COLLATE 'utf8mb4_unicode_ci',
  `item_number` int(11) NOT NULL,
  `ncf_competency` varchar(255) NOT NULL COLLATE 'utf8mb4_unicode_ci',
  `competency_code` varchar(50) NOT NULL COLLATE 'utf8mb4_unicode_ci',
  `correct_option` char(1) NOT NULL COLLATE 'utf8mb4_unicode_ci' COMMENT 'A, B, C, or D',
  `status` tinyint(4) NOT NULL DEFAULT 1,
  `created_by` bigint(20) unsigned NOT NULL,
  `created_at` timestamp(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_by` bigint(20) unsigned DEFAULT NULL,
  `updated_at` timestamp(6) NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  PRIMARY KEY (`id`),
  KEY `FK_omr_question_master_created_by` (`created_by`),
  KEY `FK_omr_question_master_updated_by` (`updated_by`),
  CONSTRAINT `FK_omr_question_master_created_by` FOREIGN KEY (`created_by`) REFERENCES `user_master` (`user_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_omr_question_master_updated_by` FOREIGN KEY (`updated_by`) REFERENCES `user_master` (`user_id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `omr_student_response` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `student_id` bigint(20) unsigned NOT NULL,
  `teacher_id` bigint(20) unsigned NOT NULL COMMENT 'The user who entered the OMR data',
  `question_id` bigint(20) unsigned NOT NULL,
  `selected_option` char(1) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci' COMMENT 'A, B, C, D, or NULL',
  `is_correct` tinyint(1) NOT NULL DEFAULT 0,
  `status` tinyint(4) NOT NULL DEFAULT 0 COMMENT '0: Draft, 1: Submitted',
  `created_by` bigint(20) unsigned NOT NULL,
  `created_at` timestamp(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_by` bigint(20) unsigned DEFAULT NULL,
  `updated_at` timestamp(6) NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_omr_student_question` (`student_id`, `question_id`),
  KEY `FK_omr_student_response_student` (`student_id`),
  KEY `FK_omr_student_response_teacher` (`teacher_id`),
  KEY `FK_omr_student_response_question` (`question_id`),
  KEY `FK_omr_student_response_created_by` (`created_by`),
  KEY `FK_omr_student_response_updated_by` (`updated_by`),
  CONSTRAINT `FK_omr_student_response_student` FOREIGN KEY (`student_id`) REFERENCES `student_master` (`student_id`) ON DELETE CASCADE ON UPDATE NO ACTION,
  CONSTRAINT `FK_omr_student_response_teacher` FOREIGN KEY (`teacher_id`) REFERENCES `user_master` (`user_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_omr_student_response_question` FOREIGN KEY (`question_id`) REFERENCES `omr_question_master` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION,
  CONSTRAINT `FK_omr_student_response_created_by` FOREIGN KEY (`created_by`) REFERENCES `user_master` (`user_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_omr_student_response_updated_by` FOREIGN KEY (`updated_by`) REFERENCES `user_master` (`user_id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
